### ISSUE TITLE
esp32cam.h library

### ISSUE THREAD

**Issue by StormingMoose** [BillNyeTheQuickScopeGuy/ESP32Cam_spider_controller#1]
ESP32Cam_spider_controller.ino asks to include esp32cam.h library.  Pardon the noob question but where is it available?

**Comment by ABA-Industries** [comment]
I forget exactly but I think this is what i used. https://github.com/yoursunny/esp32cam
Also the board name is AI Thinker ESP32-Cam

**Comment by StormingMoose** [comment]
Thank you, curious what pins you used.
